#!/usr/bin/php
<?php

# argv[1] = usernick, argv[2] = channel, argv[3] = action_args

error_reporting(0);

function action_calc($expr)
{
	$result=explode("\n",shell_exec('/bin/echo -E '.escapeshellarg($expr).' | /usr/bin/timeout 3 /usr/bin/bc 2>&1'));

	# this prevents chat being flooded. only catch the first result.
	$result=$result[0];
	return $result;
}

if($argv[3] != "")
{
	echo "$argv[1]: ".action_calc($argv[3]);
	echo "\n";
	exit(1);
}
exit(0);
