#!/bin/sh

# argv[1] = usernick, argv[2] = channel, argv[3] = action_args

/usr/games/fortune -c -a -s $3

# return 1 to output result to the public irc channel. return 2 for a private message instead.
exit 1
