#!/usr/bin/php
<?php
# argv[1] = usernick, argv[2] = channel, argv[3] = action_args

error_reporting(0);

if(!class_exists('DOMDocument'))
{
	die('DOM / XML is not installed!');
}
if(!function_exists('curl_init'))
{
	die('CURL is not installed!');
}

function url_get_title($query)
{
	$query = urlencode($query);
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, 'https://lite.duckduckgo.com/lite/?q='.$query);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
	curl_setopt($ch, CURLOPT_TIMEOUT, 5);
	curl_setopt($ch,CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0');
	$html = curl_exec($ch);
	curl_close($ch);

	if(strlen($html) > 0)
	{
		return parse_search($html);
	}
}

function parse_search($html)
{
	$start_flag = 0;
	$result='';
	libxml_use_internal_errors(true);
	$dom = new DOMDocument;
	$dom->loadHTML($html);
	$list = $dom->getElementsByTagName('td');

	foreach($list as $key=>$value)
	{
		$line = trim($value->nodeValue);
		//echo "key: [$key] => value: [$line]\n";

		if(substr($line, 0, 2) == "1.")
		{
			// start of what we want
			$start_flag = 1;
			continue;
		}
		if(substr($line, 0, 2) == "2.")
		{
			// got everything we want.
			break;
		}
		if($start_flag == 1)
		{
			// collect what we want
			$result = $result.$line."\n";
		}
	}

	// cleanup the results
	$result_array = explode("\n", $result);
	$final_result = array();
	foreach($result_array as $value)
	{
		if(ord($value) > 126) { continue; }
		if(trim($value)==""){ continue; }
		$final_result[] = $value;
	}
	return implode("\n", $final_result)."\n";
}

if($argv[3] != "")
{
	echo url_get_title($argv[3]);
	exit(1);
}
exit(0);
